/* global __dirname */
const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");

/**
 * "Powered by Softmato" on the native Android splash screen.
 *
 * expo-splash-screen can only draw one centred image (`windowSplashScreenAnimatedIcon`),
 * and on Android 12+ the system masks that icon into a circle — so the
 * attribution cannot be baked into `splash-logo.png`, it would be cropped away.
 *
 * Android 12 added a slot built for exactly this: `windowSplashScreenBrandingImage`,
 * an image the system draws at the bottom of the splash screen. androidx's
 * `core-splashscreen` compat library does not forward that attribute, so it is
 * set directly in a `values-v31` override of the splash theme (API 31+ is the
 * only place the attribute exists anyway).
 *
 * A `values-v31/styles.xml` entry *replaces* the base one rather than merging,
 * so the four items expo-splash-screen writes into `values/styles.xml` are
 * mirrored here. If the splash config in app.json grows an option that changes
 * that theme, mirror it below as well.
 *
 * On Android 11 and below the system has no branding slot; there the attribution
 * comes from the JS overlay in `components/branding/brand-splash.tsx`, which
 * renders the same strip at the same size.
 */

const DRAWABLE_NAME = "splashscreen_branding";
const SOURCE_RES_DIR = path.join(__dirname, "splash-branding-res");

const STYLES_V31 = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withSplashBranding.js — edits here are overwritten on prebuild. -->
<resources>
  <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
    <item name="windowSplashScreenBackground">@color/splashscreen_background</item>
    <item name="windowSplashScreenAnimatedIcon">@drawable/splashscreen_logo</item>
    <item name="postSplashScreenTheme">@style/AppTheme</item>
    <item name="android:windowSplashScreenBehavior">icon_preferred</item>
    <item name="android:windowSplashScreenBrandingImage">@drawable/${DRAWABLE_NAME}</item>
  </style>
</resources>
`;

function writeFileIfChanged(filePath, contents) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, "utf8") === contents) return;
  fs.writeFileSync(filePath, contents);
}

module.exports = function withSplashBranding(config) {
  return withDangerousMod(config, [
    "android",
    (mod) => {
      const resDir = path.join(
        mod.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
      );

      // One PNG per density bucket, sized so the strip lands at 136×55dp.
      for (const bucket of fs.readdirSync(SOURCE_RES_DIR)) {
        const source = path.join(SOURCE_RES_DIR, bucket, `${DRAWABLE_NAME}.png`);
        if (!fs.existsSync(source)) continue;

        const targetDir = path.join(resDir, bucket);
        fs.mkdirSync(targetDir, { recursive: true });
        fs.copyFileSync(source, path.join(targetDir, `${DRAWABLE_NAME}.png`));
      }

      const valuesV31 = path.join(resDir, "values-v31");
      fs.mkdirSync(valuesV31, { recursive: true });
      writeFileIfChanged(path.join(valuesV31, "styles.xml"), STYLES_V31);

      return mod;
    },
  ]);
};
